version: 2.1
orbs:
  node: circleci/node@1.1.6

commands:
  install_dependencies:
    steps:
      - run: yarn install
      - run: yarn lerna link

jobs:
  build-storybook:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Create GitHub Deployment
                command: sh ./scripts/deployment/start.sh > deployment
            - install_dependencies
            - run: yarn storybook:build
            - store_artifacts:
                path: build-storybook
            - run:
                name: Add GitHub Deployment success status
                command: sh ./scripts/deployment/end.sh success
                when: on_success
            - run:
                name: Add GitHub Deployment error status
                command: sh ./scripts/deployment/end.sh error
                when: on_fail
  lint-and-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - node/with-cache:
          steps:
            - install_dependencies
            - run: yarn lint .
            - run: yarn test
workflows:
  # lint-and-test:
  #   jobs:
  #     - lint-and-test
  deploy:
    jobs:
      - lint-and-test
      - build-storybook
